spring:
  main:
    # Quita el banner de Spring Boot en "off", "console" tambien es buena opcion.
    banner-mode: "console"
    # Quita los logs de arranque de spring
    log-startup-info: false
  application:
    name: jbreak-shell
  shell:
    config:
      location: classpath:stty

application:
  title: JBreak-shell
  version: 0.0.1