spring:
  main:
    # Quita el banner de Spring Boot, "console" tambien es buena opcion.
    banner-mode: "console"
    # Quita los logs de arranque de spring
    log-startup-info: false
  application:
    name: jbreak-cli
  shell:
    interactive:
      enable: true

application:
  title: JBreak-CLI
  version: 0.0.1